### ISSUE TITLE
Swift setup cannot create directory error

### ISSUE THREAD

**Issue by alex-taffe** [compnerd/swift-build#302] opened 2020-09-29 18:56 UTC
When running the latest installer build, I ran into the issue:
```
Cannot create the directory 'C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\windows\x86_6MSVCRT.swiftmodule'. A file with this name already exists. Please rename or remove the file and click retry, or click Cancel to exit
```
This should most likely have an overwrite option (or overwrite by default), as it was created by a previous installer.

**Comment by alex-taffe** [comment] 2020-09-29 18:59
This also occurred in that directory with:
```
SwiftOne.swiftmodule
Swift.swiftmodule
WinSDK.swiftmodule
```

Manually deleting the files solved the issue and allowed the installation to succeed

**Comment by compnerd** [comment] 2020-09-29 20:44
Ah, the install over the existing installation process is currently not working :-(.  I want to figure out how to do that (#298 was my initial attempt to get that to work).  The problem is that for the clang resource headers, I use a tool to enumerate the headers and install them rather than explicitly list them out.  If we can get that fixed up, we should be able to support in-place upgrades.  The current workaround is to run the uninstaller first :-( (you should be able to go to "Add/Remove Progarms" and select Modify and then uninstall.

**Comment by compnerd** [comment] 2023-12-14 22:13
This should be fixed at this point with the installer overhaul in the 5.10 release.

**Closed by compnerd** 2023-12-14 22:13 UTC
